import {test} from 'node:test';
import assert from 'node:assert/strict';
import {searchCatalog,generateGuidedProposal, type GuidedFormInput} from '../src/services/catalogSearch';
import {checkSubmission} from '../src/services/validation';
import {LEGACY_CATALOG_DATA} from '../src/data/catalog';
const base: GuidedFormInput={setting:'ricovero',flusso:'SDO',diagnosiFinaleDoc:'non_definita',acuzie:'non_documentata',condizioniAssociate:[],nonDocumentatoCondizioni:true,procedureEseguite:[],accessoChirurgico:'non_documentato',dispositiviImpiantati:[],cpapApplicata:false,insufficienzaRespDocumentata:false,antibiogrammaResistenzaDoc:false,noteTestuali:''};
test('empty query applies terminal filter before limit',()=>{assert.deepEqual(new Set(searchCatalog({query:'',terminalOnly:true,limit:9999})),new Set(LEGACY_CATALOG_DATA.filter(e=>e.terminal)));});
test('exact code without punctuation ranks first',()=>{assert.equal(searchCatalog({query:'I501'})[0]?.code,'I50.1');});
test('typo search recovers colecistite sample without inventing results',()=>{const exact=searchCatalog({query:'colecistite'}); assert.ok(exact.length); assert.deepEqual(searchCatalog({query:'colecisttie'}).map(e=>e.code),exact.map(e=>e.code));});
test('punctuation alone is not an all-catalog search',()=>assert.equal(searchCatalog({query:'...'}).length,0));
test('system filter never crosses classifications',()=>assert.ok(searchCatalog({query:'',system:'CIPI'}).every(e=>e.system==='CIPI')));
test('unknown PS diagnosis never becomes dispnea or excluded infarction',()=>{for(const d of ['non_definita','sospetto_escluso']) assert.equal(generateGuidedProposal({...base,setting:'PS/OBI senza ricovero',diagnosiFinaleDoc:d}).primaryDiagnosis,null);});
test('TAVI with unknown access has no default procedure',()=>assert.equal(generateGuidedProposal({...base,procedureEseguite:['tavi']}).procedures.length,0));
test('robot without a resolved reference procedure never emits W',()=>assert.equal(generateGuidedProposal({...base,procedureEseguite:['tavi'],dispositiviImpiantati:['robot']}).procedures.length,0));
test('CPAP and generic respiratory failure do not imply acute failure',()=>{for(const documented of [false,true]) assert.equal(generateGuidedProposal({...base,cpapApplicata:true,insufficienzaRespDocumentata:documented}).secondaryDiagnoses.length,0);});
test('resistance checkbox does not imply a specific resistance code',()=>assert.equal(generateGuidedProposal({...base,antibiogrammaResistenzaDoc:true}).secondaryDiagnoses.length,0));
test('no unverified guided proposal enables scoring',()=>{const p=generateGuidedProposal({...base,diagnosiFinaleDoc:'stemi_anteriore',procedureEseguite:['ptca_stent']});assert.equal(p.scoringStatus.scoringEnabled,false);assert.ok(p.missingInformation.length);assert.ok(p.procedures.every(p=>!p.confirmed));assert.equal(p.procedures.length,1);});
const answer={primaryDiagnosisCode:'I50.1',primaryDiagnosisDesc:'',secondaryDiagnoses:[],procedureCodes:[]};
test('plausible code never receives an invented validity or score',()=>{const result=checkSubmission(answer); assert.equal(result.status,'not_evaluable');assert.equal(result.score,null);});
test('CM seven-character example is rejected without truncation',()=>assert.equal(checkSubmission({...answer,primaryDiagnosisCode:'S72.032A'}).status,'invalid'));
test('missing and duplicate codes are actual input errors',()=>{assert.equal(checkSubmission({...answer,primaryDiagnosisCode:''}).status,'invalid'); assert.equal(checkSubmission({...answer,secondaryDiagnoses:[{code:'i501',desc:''}]}).status,'invalid');});
